name: CI
on:
  pull_request:
    branches: ['master']
  
jobs:
  comment:
    if: ${{ github.actor != github.repository_owner }}
    runs-on: ubuntu-latest
    name: Comment on PR
    steps:
      - name: Comment
        run: |
          curl
            -X POST
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
            -H "Accept: application/vnd.github.v3+json"
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
            -d '{"body":"Hey @${{ github.actor }}!\nFirst of all, thank you for your pull request, however I noticed that you want to merge it into the default branch, `master`.\nAs only thoroughly tested code appears on this repository's default branch, please change the base branch to `dev`, as [CONTRIBUTING.md](../../CONTRIBUTING.md) states:\n> Please open all of your pull requests against the `dev` branch\n\nThanks in advance and happy hacking!"}'
            --fail
