name: CI / Markdown
on: [push, pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown Files
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - id: mdl
        name: Run Markdownlinter
        uses: actionshub/markdownlint@main
